<?php

// routes.php - Define available routes
$routes = [
    '' => 'admin/dashboard.php',
    'dashboard' => 'admin/dashboard.php',
    'dispatchDashboard' => 'admin/dispatch-dashboard1.php',
    'dashboard-trailer' => 'admin/dashboard-trailer.php',
    'dashboard-truck' => 'admin/dashboard-truck.php',
    'dashboard-attendance' => 'admin/dashboard-attendance.php',
    'dispatch' => 'admin/dispatch.php',
    'driversReport' => 'admin/drivers-report.php',
    'drivers' => 'admin/drivers.php',
    'print' => 'admin/print_dispatch.php',
    'printcth' => 'admin/print_dispatchCTH.php',
    'gate' => 'admin/gate.php',
    'mybook' => 'admin/mybooking.php',
    'allbook' => 'admin/allbooking.php',
    'addbook' => 'admin/addbooking.php',
    'monitoring' => 'admin/monitoring.php',
    'abcmonitoring' => 'admin/abcmonitoring.php',
    'dolemonitoring' => 'admin/dolemonitoring.php',
    'dmmonitoring' => 'admin/dmmonitoring.php',
    'farmmonitoring' => 'admin/farmmonitoring.php',
    'sumimonitoring' => 'admin/sumimonitoring.php',
    'cthmonitoring' => 'admin/cthmonitoring.php',
    'trailer' => 'admin/trailer.php',
    'tripReport' => 'admin/trip-report.php',
    'attendReport' => 'admin/attend-report.php',
    'trailerReport' => 'admin/trailer-report.php',
    'truckReport' => 'admin/truck-report.php',
    'truck' => 'admin/truck.php',
    'unitProfile' => 'admin/addunit-page.php',
    'unitEditProfile' => 'admin/updateunit-page.php',
    'containerMonitoring' => 'admin/container_monitoring.php',
    'genset' => 'admin/genset.php',
    'user' => 'admin/user.php',
    'segment' => 'admin/segment.php',
    'bookingSegments' => 'admin/booking-segments.php',
    'incidents' => 'admin/incidents.php',
    'profile' => 'admin/profile.php',
    'logout' => 'logout.php',
    'login' => 'login.php',
    'index' => 'login.php',
    // Dispatcher routes
    'dispatch-dashboard' => 'dispatcher/dashboard.php',
    'dispatch-dispatchDashboard' => 'dispatcher/dispatch-dashboard1.php',
    'dispatch-dashboard-trailer' => 'dispatcher/dashboard-trailer.php',
    'dispatch-dashboard-truck' => 'dispatcher/dashboard-truck.php',
    'dispatch-dashboard-attendance' => 'dispatcher/dashboard-attendance.php',
    'dispatch-dispatch' => 'dispatcher/dispatch.php',
    'dispatch-dispatchTest' => 'dispatcher/dispatch-test.php',
    'dispatch-driversReport' => 'dispatcher/drivers-report.php',
    'dispatch-drivers' => 'dispatcher/drivers.php',
    'dispatch-print' => 'dispatcher/print_dispatch.php',
    'dispatch-print1' => 'dispatcher/print_dispatch1.php',
    'dispatch-printJob' => 'dispatcher/print_job_ticket.php',
    'dispatch-printcth' => 'dispatcher/print_dispatchCTH.php',
    'dispatch-gate' => 'dispatcher/gate.php',
    'dispatch-mybook' => 'dispatcher/mybooking.php',
    'dispatch-allbook' => 'dispatcher/allbooking.php',
    'dispatch-addbook' => 'dispatcher/addbooking.php',
    'dispatch-monitoring' => 'dispatcher/monitoring.php',
    'dispatch-abcmonitoring' => 'dispatcher/abcmonitoring.php',
    'dispatch-dolemonitoring' => 'dispatcher/dolemonitoring.php',
    'dispatch-dmmonitoring' => 'dispatcher/dmmonitoring.php',
    'dispatch-farmmonitoring' => 'dispatcher/farmmonitoring.php',
    'dispatch-sumimonitoring' => 'dispatcher/sumimonitoring.php',
    'dispatch-cthmonitoring' => 'dispatcher/cthmonitoring.php',
    'dispatch-trailer' => 'dispatcher/trailer.php',
    'dispatch-tripReport' => 'dispatcher/trip-report.php',
    'dispatch-attendReport' => 'dispatcher/attend-report.php',
    'dispatch-trailerReport' => 'dispatcher/trailer-report.php',
    'dispatch-truckReport' => 'dispatcher/truck-report.php',
    'dispatch-truck' => 'dispatcher/truck.php',
    'dispatch-unitProfile' => 'dispatcher/addunit-page.php',
    'dispatch-unitEditProfile' => 'dispatcher/updateunit-page.php',
    'dispatch-containerMonitoring' => 'dispatcher/container_monitoring.php',
    'dispatch-genset' => 'dispatcher/genset.php',
    'dispatch-user' => 'dispatcher/user.php',
    'dispatch-segment' => 'dispatcher/segment.php',
    'dispatch-bookingSegments' => 'dispatcher/booking-segments.php',
    'dispatch-incidents' => 'dispatcher/incidents.php',
    'dispatch-profile' => 'dispatcher/profile.php',
    // Gate-Guard routes
    'gate-dashboard' => 'gate/dashboard.php',
    'gate-checkin'   => 'gate/checkin.php',
    'gate-incident'  => 'gate/incident.php',
    'gate-profile'   => 'gate/profile.php',
    'gate-logout'    => 'logout.php',
    'gate-login'     => 'login.php',
    // Driver routes
    'driver-dashboard' => 'driver/dashboard.php',
    'driver-profile' => 'driver/profile.php',
    'driver-bookinglist' => 'driver/bookinglist.php',
    'driver-unit' => 'driver/unit.php',
    'driver-tripReport' => 'driver/trip-report.php',
    'driver-driversReport' => 'driver/drivers-report.php',
    // Phase 5 — Driver PWA
    'driver-checklist' => 'driver/checklist.php',
    'driver-pod' => 'driver/pod.php',
    'driver-gateless' => 'driver/gateless.php',
    'driver-jackup' => 'driver/jackup.php',
    'driver-breakdown' => 'driver/breakdown.php',
    'driver-messages' => 'driver/messages.php',
    // Shop routes
    'shop-dashboard' => 'shop/dashboard.php',
    'shop-rescue' => 'shop/rescue.php',
    'shop-shop' => 'shop/shop.php',
    'shop-manpower' => 'shop/manpower.php',
    'shop-rescueReport' => 'shop/rescue-report.php',
    'shop-shopReport' => 'shop/shop-report.php',
    'shop-profile' => 'shop/profile.php',
    // HR (User) routes
    'hr-dashboard' => 'HR/dashboard.php',
    'hr-profile' => 'HR/profile.php',
    'hr-drivers' => 'HR/drivers.php',
    'hr-performance' => 'HR/performance.php',
    'hr-violationReport' => 'HR/violationReport.php',
    'hr-tripReport' => 'HR/trip-report.php',
    'hr-attendReport' => 'HR/attend-report.php',
    // HR Admin routes
    'hra-dashboard' => 'HR Admin/dashboard.php',
    'hra-profile' => 'HR Admin/profile.php',
    'hra-drivers' => 'HR Admin/drivers.php',
    'hra-performance' => 'HR Admin/performance.php',
    'hra-violationReport' => 'HR Admin/violationReport.php',
    'hra-tripReport' => 'HR Admin/trip-report.php',
    'hra-attendReport' => 'HR Admin/attend-report.php',
    // Visual routes
    'visual-dashboard' => 'data-visual/dashboard.php',
    'visual-profile' => 'data-visual/profile.php',
    'visual-truckReport' => 'data-visual/truck-report.php',
    'visual-trailerReport' => 'data-visual/trailer-report.php',
];

// Get the route from URL
$route = $_GET['route'] ?? 'dashboard';

// Check if the route exists, otherwise show a 404 page
if (array_key_exists($route, $routes)) {
    require $routes[$route];
} else {
    require 'admin/404.php';
}
?>
